#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

OneNote = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAACfJJ"
    "REFUWIWll2uMnFUZx3/nvNeZeWd29trbbne3F3phpaVLsS1UokKpWDUoUCOC+sFoNBqJhmjw"
    "A0aiAaME0Rr9poJNNGoqglWIAkpbkJaitNBq6V663V7Y7e7M7Mx7O+f44d2d3oyaeJKTSU7e"
    "d57f+zz//3POEVwyntr6lPfL0Z3vdaTc0tLasrZWrS1AmbwUAhAIcekbF68ZA9KSOLYNAhEl"
    "6m8qtB/ccWjH7w3m0pdpvqqNFp9Y/ZFPWfA13/O7PN/DcRxKpRJRHGNb1mwAg0AghEBIiWVJ"
    "pJQImf3KORoD2mgsy6JcLnPl8rftePu9N3z2UgAbwNxurI+v3P6473nbi8UiuVwOx3FoaWmh"
    "r6+P3oEltC/pJOgooZUiiRKSNEGlilSlqFShlSZNU9I0xWiN0jqDSDVuwWVtz0Ar916WgAzg"
    "Ywe3P5DL+dtbW8sUCgVc16W3t5cNN26i9ap5vPLnlxl65ji105Xsa4XAth2kFBhjMMagtEal"
    "KUmSEDZCKtUK4+PjTExOcuXgAP2f70k9zyOKoosArHuu/syyWIU/a20ty2KxiO/79Pf38+7t"
    "N1PPx7z4+PP0tnTTGpQpFkv4OR/HcbBduwmjtUHplCRNSXSKFhrhSuy8g1/y6eydR9/qJZWD"
    "ew/4lZFzUfKgPqO1zjJQrU9/MpfP2b7v4zguLeUym26+nhmrwck/HWfjtRto1BvU6jN4C/N0"
    "9XUjHIHl2Nieje3a2J6D47s4noPt2AgDaaxIwogkTIjCiLgRbX5kx3c3b9AbvtjV1fX3sbGx"
    "DMB27Xd6nott21iWZOXKFeSWt/Dcj37Pxg2bSJOEVCmSNKHQ3Urf+qWXF/LSYcCyDMqSCJkJ"
    "FgNKafxCPqqX681HJdosbm/vIJ/P4/k+fdcsY+9vnifIB0RhRBTF1KM6Lx/ez+6f/pZvffzr"
    "/OLhn/13iIwjm8ZgMGilCPK5eOPGje7Y2JgAkFopZ2rqHFEUkc/lKPe3cfCP+ykWi4RhgzBs"
    "UJmpMDQyhKNtysUy5c7W/wlgNjo61ehUk8Qpt2++9WvvW77l2Iu/eG6jZVmZCwC01khpcW5q"
    "isZMiJSSarVKmqYkYcLAlQPc8MktLOxb9O9jGcOpA6NMj55j5QfWMNdz/vHUIU7uG6JtYB5W"
    "r4/UckE+yHPwtdfytm3P9oFZK0kpmDg7gW1b1GozgCFNFXEcISLIF/KXBdZKc+rAKCMvvImO"
    "FQuu6Wmuv/Tos0yPTJJvD5CORRzGtBfa0EqzeOniMIoipNYGow1aG4yEKAwRQlCpTFOpVKhW"
    "q0xMTzI+cYq//Po5fv7txxk9OtwEOPv3cSpjUyS1CCfn0LK4DaM1ex5+hsL8IlbOIZxuUOwr"
    "k4YJLbkSGLjr7o+GmQaMQRuDMRpjDEmUoJWmVq1Rq9WozVQ5O/0WURRx6LcH+OuuvcRh3ASY"
    "t3YRy28ZIK5FJI2Ecn87L//oL7QsbmPpjauYHp5EuJLCvCJJFBOqCKUV5QWdIYBtyIJrnYEI"
    "IUjShNpMLWsyRiO1hJLF5354L7kgl9nqgjFx9DQIKPe388/dhzFKM3DHIC/98HmkJelauwhj"
    "DGEj5Fxjirws6vu+cV/8Vb6KbdCzGtBgNFJKDBDHMUJkm4uHQ3t7B/ni5RoAGN8/ihACy7UY"
    "PzDC5i/fTFpPGH72KMKSzB/sJgpDkGgVcMQJ3DNvvPFGBcBWRmVfPzstaSGFIFUKywKBBAl+"
    "KU+apNTOVSl3nbdh0kg4e3gct+Bx4sXjXHfvFqRtcfy5QySNhL53L8dyLXTd0NrZFv54z847"
    "Jp6YGDl69Gj1sccew85qn02tsgxIKcGYbK8WUKPOuQOvc9+We0iE4jt/3NEEOHVgFDRElZDV"
    "d6zDL+cwxvDP3x1GAH3vWoExmdMQxPl8fuq2791W7+/vNwByzoLGZJ1KSonjOEhpYVkWtutQ"
    "rdVoaS1z3ZbN3HTn1ku8fwJpSTpXzmfR+t5ME2+cpjo6zYJ1veQ7AzCZ04ZeP164c+BDf1h/"
    "cO2TO3fu9DIRapo2VEohpMBxnOzAIQQCwaLOhVy1bZDrtr3jotpXT0wxPTKJkIIVH1zTPN4c"
    "ffI1EhWz7JbVTVCjDbXJqiOEWGWkjiYnJ20gkobzNtRKI0QGYNsWjuPguS6BU6BUKl0mvhP7"
    "htBK03P9EnJtmUCjSoPRvW9S7m2nY9X8ZkfURuNg49kuxhAvXbpUZxm4oAcorZBC4roejuvg"
    "eR6246ClRhvN8OtD5IIcXT3zSKOU0wdPYDkWfe+8ogk18udjYGDZTavnCpVpQBsCuwA5g23J"
    "+MiRI5kGmikyWRmkkHiei+/5eJ5HbGLGzo3z5CO/5geffZj9z7yUie+VE6RRyvzBHtzAOy/K"
    "/WMUgiLd1/Yx/IejWQJm/3+mPkOsEyxpxXfffbe5IAOz7dhoLGnheT6e5+P7HlGcUJ+pM7hp"
    "kGJniWWbVgJw8qVhhBD0vmPZeUvOxMSnQoJ8kQMP7mHhe3ovEuxEbRLXdXFybjQ4OJiVYI5O"
    "G41RGms2A9n0WBAUCFoCbvz0LeSCrM71MzVUPaVrYCHB/PPaqI5O4/t5gu4SS25fgczbNGr1"
    "bFfWhiiKSJPUOK5Te+ihh8y2bduQ6LkSzG3JEtfJgnueRyGXpxy04OX8ZqDaaIXSwjJLtqy8"
    "SJTSkVzxibdx1T3XZva74B5gjOHqm6555Sd7d354Iqh+ZdOmTSrLQBNAo5RGCInjOriui+u6"
    "VMMaJ86OMb3jl0yceottn7oVt+iw6s6rkZa8CKC8tH1OdzB7keECDQxcNXDk/dtv/dVdd92V"
    "zh1KpdYarTVKqWYfsG171oo2Q6dHaEQNTr98giN7DiOEoPWKzsuCXzrELIO4AML3c/VDhw6Z"
    "ueAAdqoUaZoSxzFJkiAAy7KxbRvbsSkVijS8mBs/fDOd3V34hdx/DDyXbpUq0jgljuLsVBzF"
    "+Dmvvnz5crN79+7zAMZoGo0QrTVJkuC5Hq7rUKvVmK5XWNTfQ7CkhZ4Vvf8mEhgMNLupRqeK"
    "uB5Rr9ZNdaoSV6vVqbAevYUtxj7/pS88+8iPv2ceffTR8wDtrR3HRk+PtoVR1v3yxQLz1/dQ"
    "CAJUmHDm2OnQwa4ZZTqMzrqlVlmgNFEmiqIwDMMpjD5jO+7JoBSMLOpZeHzt2wffvP/++0d3"
    "7dr1lud508PDw/Wtt20NOzo6LrqhCoMR28vv23Z25uwXt9xy0+bbbr19ZOjY0L5Toyf3lb32"
    "vfu+v+tvjy18/oEX9ryw3cAZ13XHisVgpLun+/j1N1x37IFvfnPsiSeemBgcHJyemZlpbN26"
    "NZ6cnFQDAwOmWq1yYb3/61j181XBpWuFQoE1a9Z0PP30072vvvpq27p163Lr16+3x8bGRBAE"
    "2db9f4x/AcYLFwfkRJP+AAAAAElFTkSuQmCC")
getOneNoteData = OneNote.GetData
getOneNoteImage = OneNote.GetImage
getOneNoteBitmap = OneNote.GetBitmap
getOneNoteIcon = OneNote.GetIcon

